version: "2"
services:
  app:
    build: ./server/app
    links:
      - db
    ports:
      - "5000:5000"
      
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    command: --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'CS5331'
